name: puntocell_flutter
description: "frontend de la app de punto cell."

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  http: ^1.2.2
  uuid: ^4.5.1
  quickalert: ^1.1.0
  flutter_launcher_icons: ^0.14.2
  intl: ^0.19.0
  flutter_localization: ^0.2.3
  window_size: ^0.1.0
  data_table_2: ^2.5.16

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:

  fonts:
    - family: blazedfont
      fonts:
        - asset: assets/fonts/Blazed.ttf
        - asset: assets/fonts/Onest-Bold.ttf
        - asset: assets/fonts/Onest-Medium.ttf
        - asset: assets/fonts/Onest-Regular.ttf
    - family: Onest
      fonts:
        - asset: assets/fonts/Onest-Bold.ttf
        - asset: assets/fonts/Onest-Medium.ttf
        - asset: assets/fonts/Onest-Regular.ttf

  assets:
    - assets/logopuntocell.png
    - assets/letraslogo.png
    - assets/logo.png

  uses-material-design: true
